// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ModelsBearing models bearing
//
// swagger:model models.Bearing
type ModelsBearing struct {

	// manufacturer
	// Example: SKF
	// Required: true
	Manufacturer *string `json:"manufacturer"`

	// model number
	// Example: 2222
	// Required: true
	ModelNumber *string `json:"modelNumber"`
}

// Validate validates this models bearing
func (m *ModelsBearing) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateManufacturer(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateModelNumber(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsBearing) validateManufacturer(formats strfmt.Registry) error {

	if err := validate.Required("manufacturer", "body", m.Manufacturer); err != nil {
		return err
	}

	return nil
}

func (m *ModelsBearing) validateModelNumber(formats strfmt.Registry) error {

	if err := validate.Required("modelNumber", "body", m.ModelNumber); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this models bearing based on context it is used
func (m *ModelsBearing) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsBearing) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsBearing) UnmarshalBinary(b []byte) error {
	var res ModelsBearing
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
