// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsOverall models overall
//
// swagger:model models.Overall
type ModelsOverall struct {

	// inner high
	// Example: 50
	InnerHigh *float64 `json:"innerHigh,omitempty"`

	// inner low
	// Example: 10
	InnerLow *float64 `json:"innerLow,omitempty"`

	// outer high
	// Example: 70
	OuterHigh *float64 `json:"outerHigh,omitempty"`

	// outer low
	// Example: 5
	OuterLow *float64 `json:"outerLow,omitempty"`

	// unit
	// Example: gE
	Unit string `json:"unit,omitempty"`
}

// Validate validates this models overall
func (m *ModelsOverall) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models overall based on context it is used
func (m *ModelsOverall) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsOverall) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsOverall) UnmarshalBinary(b []byte) error {
	var res ModelsOverall
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
