// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsOrigin models origin
//
// swagger:model models.Origin
type ModelsOrigin struct {

	// id
	ID string `json:"id,omitempty"`

	// provider
	Provider string `json:"provider,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this models origin
func (m *ModelsOrigin) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models origin based on context it is used
func (m *ModelsOrigin) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsOrigin) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsOrigin) UnmarshalBinary(b []byte) error {
	var res ModelsOrigin
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
