// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProblemsValidationProblem problems validation problem
//
// swagger:model problems.ValidationProblem
type ProblemsValidationProblem struct {

	// CorrelationID, an unique identifier for tracing this issue in server logs.
	CorrelationID string `json:"correlationId,omitempty"`

	// Detail, a human-readable explanation specific to this occurrence of the problem.
	Detail string `json:"detail,omitempty"`

	// Instance, a URI reference that identifies the specific resource on which the problem occurred.
	Instance string `json:"instance,omitempty"`

	// reasons
	Reasons []*ProblemsValidationReason `json:"reasons"`

	// Status, the HTTP status code associated with this problem occurrence.
	Status int64 `json:"status,omitempty"`

	// Title, a short, human-readable summary of the problem type.
	// This should always be the same value for the same Type.
	Title string `json:"title,omitempty"`

	// Type, a URI reference that identifies the problem type.
	// When dereferenced this should provide human-readable documentation for the
	// problem type. When member is not present it is assumed to be "about:blank".
	Type string `json:"type,omitempty"`
}

// Validate validates this problems validation problem
func (m *ProblemsValidationProblem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReasons(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProblemsValidationProblem) validateReasons(formats strfmt.Registry) error {
	if swag.IsZero(m.Reasons) { // not required
		return nil
	}

	for i := 0; i < len(m.Reasons); i++ {
		if swag.IsZero(m.Reasons[i]) { // not required
			continue
		}

		if m.Reasons[i] != nil {
			if err := m.Reasons[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("reasons" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("reasons" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this problems validation problem based on the context it is used
func (m *ProblemsValidationProblem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateReasons(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProblemsValidationProblem) contextValidateReasons(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Reasons); i++ {

		if m.Reasons[i] != nil {
			if err := m.Reasons[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("reasons" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("reasons" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProblemsValidationProblem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProblemsValidationProblem) UnmarshalBinary(b []byte) error {
	var res ProblemsValidationProblem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
