name: Validate

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
        id: go

      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52

      - name: Run unit tests
        run: go test -short ./...

      - name: Check uncommitted changes
        run: |
          make internal/models
          git update-index --refresh
          git diff-index --quiet HEAD --
