name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.44.0

      - name: Run unit tests
        run: go test -v -coverprofile=coverage.out -covermode=count ./...

      - name: Generate models
        run: make internal/models

      - name: Check changes
        run: |
          git update-index --refresh
          git diff-index HEAD --
